INSERT INTO products (name, name_mm, description, description_mm, category, brand, price, stock_quantity)
VALUES ('iPhone 15 Pro', 'အိုင်ဖုန်း ၁၅ ပရို',
        'The latest premium smartphone with A17 Bionic chip and ProMotion display.',
        'A17 Bionic ချစ်ပ်နှင့် ProMotion မျက်နှာပြင်ပါဝင်သော နောက်ဆုံးပေါ် ပရီမီယမ်စမတ်ဖုန်း။', 'Electronics', 'Apple',
        1299.00, 45),
       ('Samsung Galaxy S23', 'ဆမ်ဆောင်း ဂလက်ဆီ S23',
        'High-end Android phone with advanced camera system and long-lasting battery.',
        'အဆင့်မြင့်ကင်မရာစနစ်နှင့် ဘက်ထရီကြာရှည်ခံသော အန်းဒရိုက်ဖုန်း။', 'Electronics', 'Samsung', 999.00, 60),
       ('Sony WH-1000XM5 Headphones', 'ဆိုနီ နားကြပ်', 'Industry-leading noise-canceling over-ear headphones.',
        'စက်မှုလုပ်ငန်းတွင် ဦးဆောင်နေသော ဆူညံသံဖျောက်နိုင်သည့် နားအုပ်နားကြပ်။', 'Electronics', 'Sony', 399.99, 150),
       ('Dell XPS 13 Laptop', 'ဒယ်လ် XPS ၁၃ လက်ပ်တော့',
        'Ultra-portable 13-inch laptop with stunning InfinityEdge display.',
        'ရင်သပ်ရှုမောဖွယ် InfinityEdge မျက်နှာပြင်ပါရှိသော အလွန်သယ်ဆောင်ရလွယ်ကူသည့် ၁၃ လက်မလက်ပ်တော့။', 'Electronics',
        'Dell', 1499.50, 20),
       ('Logitech MX Master 3S Mouse', 'လိုဂျီတက် မောက်စ်', 'Ergonomic, high-precision wireless mouse for power users.',
        'စွမ်းဆောင်ရည်မြင့် အသုံးပြုသူများအတွက် သက်တောင့်သက်သာရှိသော တိကျမှုမြင့် ကြိုးမဲ့မောက်စ်။', 'Electronics',
        'Logitech', 99.99, 300),
       ('Nike Air Max 270', 'နိုင်ကီး အဲမက်စ် ၂၇၀',
        'Casual lifestyle sneaker with a large Max Air unit for cushioning.',
        'ကူရှင်အတွက် Max Air ယူနစ်ကြီးတစ်ခုပါရှိသော ပေါ့ပေါ့ပါးပါး ဖိနပ်။', 'Footwear', 'Nike', 150.00, 120),
       ('Adidas Ultraboost 22', 'အာဒီဒတ်စ် အယ်ထရာဘွတ်စ် ၂၂',
        'High-performance running shoes designed for maximum energy return.',
        'စွမ်းအင်ပြန်ရရှိမှုအများဆုံးဖြစ်စေရန် ဒီဇိုင်းထုတ်ထားသော စွမ်းဆောင်ရည်မြင့် အပြေးဖိနပ်။', 'Footwear', 'Adidas',
        190.00, 95),
       ('Timberland Waterproof Boots', 'တင်ဘာလန်း ရေစိုခံ ဘွတ်ဖိနပ်',
        'Classic waterproof boots for rugged outdoor use.',
        'ကြမ်းတမ်းသောပြင်ပအသုံးပြုရန်အတွက် ဂန္ထဝင် ရေစိုခံ ဘွတ်ဖိနပ်။', 'Footwear', 'Timberland', 180.00, 70),
       ('Levi''s 501 Original Jeans', 'လီဗိုင်း ၅၀၁ မူရင်း ဂျင်းဘောင်းဘီ',
        'Timeless straight-leg jeans with a button fly.',
        'ခလုတ်ပါသော အိတ်လိုက်ပုံစံဖြောင့်တန်းသည့် အချိန်တိုင်း ဝတ်ဆင်နိုင်သော ဂျင်းဘောင်းဘီ။', 'Apparel', 'Levi''s',
        79.50, 250),
       ('The North Face Puffer Jacket', 'မြောက်မျက်နှာ ပွဖောင်းအင်္ကျီ',
        'Warm, insulated jacket perfect for cold weather.',
        'အေးမြသောရာသီဥတုအတွက် အံဝင်ခွင်ကျဖြစ်စေသော နွေးထွေးသည့် အပူခံအင်္ကျီ။', 'Apparel', 'The North Face', 249.00,
        40),
       ('Kindle Paperwhite', 'ကင်ဒဲလ် ပေပါဝှိုက်', 'Waterproof e-reader with an adjustable warm light.',
        'ချိန်ညှိနိုင်သော အပူပေးမီးပါရှိသည့် ရေစိုခံ အီး-ဖတ်စက်။', 'Electronics', 'Amazon', 139.99, 180),
       ('Nintendo Switch OLED', 'နင်တန်ဒို စကွစ်ခ်ျ OLED', 'Hybrid console with a vibrant OLED screen.',
        'တက်ကြွသော OLED မျက်နှာပြင်ပါရှိသည့် Hybrid ဂိမ်းစက်။', 'Electronics', 'Nintendo', 349.00, 55),
       ('Apple Watch Series 9', 'အက်ပဲလ် နာရီ စီးရီး ၉', 'Advanced smartwatch for health, fitness, and connectivity.',
        'ကျန်းမာရေး၊ ကြံ့ခိုင်ရေးနှင့် ချိတ်ဆက်မှုများအတွက် အဆင့်မြင့် စမတ်နာရီ။', 'Electronics', 'Apple', 429.00, 110),
       ('KitchenAid Stand Mixer', 'မီးဖိုချောင် ကူညီ ထမင်းနယ်စက်', 'Powerful stand mixer for baking and cooking.',
        'မုန့်ဖုတ်ခြင်းနှင့် ချက်ပြုတ်ခြင်းအတွက် စွမ်းအားကောင်းသော ရပ်တည်နေသောမစ်ဆာ။', 'Home Appliances', 'KitchenAid',
        329.00, 30),
       ('Dyson V15 Detect Vacuum', 'ဒိုင်ဆွန် V15 ဖုန်စုပ်စက်',
        'Cordless stick vacuum with laser illumination for dust detection.',
        'ဖုန်မှုန်များကို သိရှိနိုင်ရန် လေဆာအလင်းရောင်ပါရှိသော ကြိုးမဲ့တုတ်ဖုန်စုပ်စက်။', 'Home Appliances', 'Dyson',
        749.00, 25),
       ('French Press Coffee Maker', 'ပြင်သစ် ဖိစက် ကော်ဖီဖျော်စက်',
        'Simple and classic method for brewing rich, full-bodied coffee.',
        'ပြည့်ဝသော ကော်ဖီအရသာအတွက် ရိုးရှင်းပြီး ဂန္ထဝင်ဖျော်စပ်နည်း။', 'Kitchenware', 'Bodum', 35.00, 200),
       ('Instant Pot Duo 7-in-1', 'ချက်ချင်းအိုး ဒူအို ၇-ခု-၁-ခု',
        'Multi-functional pressure cooker, slow cooker, rice cooker, and more.',
        'ဖိအား cooker, နှေးကွေး cooker, ထမင်းပေါင်းအိုး စသည်တို့ပါသော ဘက်စုံသုံး မီးဖိုချောင်သုံးပစ္စည်း။',
        'Home Appliances', 'Instant Pot', 89.99, 160),
       ('Rolex Submariner Watch', 'ရိုလက်စ် ရေငုပ်သမား နာရီ', 'Iconic luxury dive watch.',
        'လူသိများသော ဇိမ်ခံ ရေငုပ်လက်ပတ်နာရီ။', 'Luxury Goods', 'Rolex', 15000.00, 5),
       ('GoPro HERO 11 Black', 'ဂိုပရို ဟီးရိုး ၁၁ အနက်ရောင်',
        'Waterproof action camera with incredible video stabilization.',
        'မယုံနိုင်စရာ ဗီဒီယိုတည်ငြိမ်မှုပါရှိသော ရေစိုခံ အက်ရှင်ကင်မရာ။', 'Electronics', 'GoPro', 499.99, 80),
       ('Canon EOS R6 Mark II', 'ကန်နွန် EOS R6 မတ်ခ် ၂', 'Full-frame mirrorless camera for professionals.',
        'ပညာရှင်များအတွက် Full-frame မှန်မဲ့ကင်မရာ။', 'Electronics', 'Canon', 2499.00, 15),
       ('Yoga Mat (Extra Thick)', 'ယောဂဖျာ (အထူပို)', 'High-density, non-slip mat for yoga and pilates.',
        'ယောဂနှင့် ပီလတ်စ်အတွက် သိပ်သည်းဆမြင့်၊ မချောသော ဖျာ။', 'Fitness', 'Gaiam', 30.00, 350),
       ('Resistance Band Set', 'ခုခံမှုကြိုး အစုံ', 'Set of five resistance bands for full-body workouts.',
        'ကိုယ်ခန္ဓာ အပြည့်အဝ လေ့ကျင့်ခန်းအတွက် ခုခံမှုကြိုး ၅ ခုပါ အစုံ။', 'Fitness', 'Sportneer', 19.99, 410),
       ('Board Game: Catan', 'ဘုတ်ဂိမ်း: ကက်တန်', 'Strategy board game of building and trading.',
        'တည်ဆောက်ခြင်းနှင့် အရောင်းအဝယ်ပြုလုပ်ခြင်းဆိုင်ရာ ဗျူဟာ ဘုတ်ဂိမ်း။', 'Toys & Games', 'Catan Studio', 49.99,
        100),
       ('LEGO Millennium Falcon', 'လီဂို မီလီနီယံ ဖော်ကွန်',
        'Large, detailed LEGO set of the iconic Star Wars spaceship.',
        'နာမည်ကြီး Star Wars အာကာသယာဉ်၏ ကြီးမားပြီး အသေးစိတ်သော LEGO အစုံ။', 'Toys & Games', 'LEGO', 849.99, 10),
       ('Electric Toothbrush', 'လျှပ်စစ် သွားတိုက်တံ', 'Rechargeable electric toothbrush with pressure sensor.',
        'ဖိအား အာရုံခံကိရိယာပါရှိသော အားပြန်သွင်းနိုင်သော လျှပ်စစ်သွားတိုက်တံ။', 'Health & Beauty', 'Oral-B', 75.00,
        220),
       ('Shampoo & Conditioner Set', 'ခေါင်းလျှော်ရည်နှင့် ဆံပင်ပျော့ဆေး အစုံ',
        'Nourishing set for dry and damaged hair.', 'ခြောက်သွေ့ပြီး ပျက်စီးနေသောဆံပင်အတွက် အာဟာရဖြည့်စုံ။',
        'Health & Beauty', 'TRESemmé', 25.99, 300),
       ('Sleek Modern Desk', 'ပြေပြစ်သော ခေတ်မီစားပွဲ', 'Minimalist writing desk with metal legs and wood top.',
        'သတ္တုခြေထောက်နှင့် သစ်သားမျက်နှာပြင်ပါရှိသော ရိုးရှင်းသော စာရေးစားပွဲ။', 'Furniture', 'IKEA', 149.00, 50),
       ('Ergonomic Office Chair', 'သက်တောင့်သက်သာရုံးကုလားထိုင်',
        'Adjustable office chair designed for long hours of work.',
        'အချိန်ကြာကြာ အလုပ်လုပ်ရန် ဒီဇိုင်းထုတ်ထားသော ချိန်ညှိနိုင်သော ရုံးကုလားထိုင်။', 'Furniture', 'Herman Miller',
        1200.00, 15),
       ('Weighted Blanket (15lb)', 'အလေးပါသော စောင် (၁၅ ပေါင်)', 'A heavy blanket for better sleep and anxiety relief.',
        'ပိုမိုကောင်းမွန်စွာ အိပ်စက်ခြင်းနှင့် စိုးရိမ်ပူပန်မှု သက်သာစေရန်အတွက် အလေးပါသောစောင်။', 'Home Goods',
        'Gravity', 199.00, 90),
       ('Air Fryer (5.8 Quart)', 'လေကြော်စက် (၅.၈ ကွာ့တ်)', 'Healthy cooking appliance that uses hot air for frying.',
        'ကြော်ရန်အတွက် လေပူကိုအသုံးပြုသော ကျန်းမာရေးနှင့်ညီညွတ်သော ချက်ပြုတ်ပစ္စည်း။', 'Home Appliances', 'Cosori',
        109.99, 140);